MAX_LENGTH = 6

IMAGE_WIDTH, IMAGE_HEIGHT = 200, 50

NEW_SHAPE = ((IMAGE_WIDTH // 4), (IMAGE_HEIGHT // 4) * 64)

BATCH_SIZE = 64

WEIGHTS_PATH_LSTM_1 = ""
WEIGHTS_PATH_LSTM_2 = ""
WEIGHTS_PATH_BiLSTM_1 = ""
WEIGHTS_PATH_BiLSTM_2 = "./weights/TrainedBiLSTM2.hdf5"

STORAGE_PATH = "./storage/"
